### ISSUE TITLE
Cannot run the sample

### ISSUE THREAD

**Issue by sangampandey** [getyoti/yoti-php-sdk#182]
Trying to run the sample but it doesn't work

![Screenshot 2020-06-18 at 00 12 24](https://user-images.githubusercontent.com/526777/84945577-7cc6c200-b0f8-11ea-9952-74b41259899a.png)

**Comment by jlmartyres** [comment]
Hi sangampandey, for any questions would you be able to email your request through to sdksupport@yoti.com ?

Please provide the following so the team can address this as soon as possible:

Computer type
OS version
Version of PHP being used
Screenshot

Thanks!

**Comment by davidgrayston** [comment]
We have now corrected the example README instructions https://github.com/getyoti/yoti-php-sdk/tree/master/examples/doc-scan
- `.env.example` should be copied to `.env`
- Please ensure the `YOTI_SDK_ID` is correct

For any further assistance please email sdksupport@yoti.com

**Comment by dapo-maraboo** [comment]
Support Email not working
The code does not work as welll
