### ISSUE TITLE
3.8.0 not on packagist

### ISSUE THREAD

**Issue by jzahedieh** [getyoti/yoti-php-sdk#257]
We're looking to upgrade to 3.8.0 your latest release, but this isn't on [packagist](https://packagist.org/packages/yoti/yoti-php-sdk) 

I believe this is because you haven't updated the [composer.json version](https://github.com/getyoti/yoti-php-sdk/blob/master/composer.json#L4), I see the following warning in composer when validating your package:

```
yoti-php-sdk$ composer validate
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
The version field is present, it is recommended to leave it out if the package is published on Packagist.
```

The error when trying to install the SDK in our project:

```
composer update
Cannot load Xdebug - it was already loaded
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yoti/yoti-php-sdk 3.8.0, found yoti/yoti-php-sdk[dev-dependabot/composer/development/phpstan/phpstan-strict-rules-tw-1.1.0, ..., dev-development, 1.0.0, ..., 1.2.2, 2.0.0, ..., 2.5.1, 3.0.0, ..., 3.7.0] but it does not match the constraint.
```

For now we're using:

`"yoti/yoti-php-sdk": "dev-master#d0d5555ffc4787e99db5a96f0060624824f9b65c"`

But this isn't really ideal for a production build.

**Comment by LuborRod** [comment]
Thank you. Already fixed.
