### ISSUE TITLE
external package conflict

### ISSUE THREAD

**Issue by jafar690** [getyoti/yoti-php-sdk#81]
you have included an external package in your source folder instead of using composer, i use that package in my project and now am getting a  `Warning: Ambiguous class resolution` conflict, the package in question is `phpseclib`.

![Screenshot from 2019-09-09 16-30-23](https://user-images.githubusercontent.com/17546030/64534965-23d32d80-d31f-11e9-9601-258ee32d1b4a.png)

**Comment by jlmartyres** [comment]
Hi Jafar,

Thank you for reporting this, the included dependancies will be removed in the next major release.

For additional queries feel free to contact our support team here: https://github.com/getyoti/yoti-php-sdk#support

**Comment by davidgrayston** [comment]
This has been resolved in `3.0.0` where dependencies have been moved into `composer.json`

The summary of changes for this release can be found here: https://github.com/getyoti/yoti-php-sdk/releases/tag/3.0.0
